"""
Example: Research Assistant using LangGraph + Amplifier@next

Demonstrates the 10% glue: Making Amplifier agents work as LangGraph nodes.

LangGraph handles: Workflow orchestration, state management, persistence
Amplifier handles: Agent intelligence, memory, checkpointing
AmpBox provides: The bridge between them (AmplifierNode)
"""

import asyncio
from typing import TypedDict

from ampbox import AmplifierNode
from langgraph.graph import END
from langgraph.graph import StateGraph


class ResearchState(TypedDict):
    """Workflow state schema - LangGraph manages this"""

    documents: list[str]
    doc_count: int
    themes: str
    report: str


async def load_documents(state: ResearchState) -> ResearchState:
    """Deterministic step: Load documents"""
    from pathlib import Path

    docs_dir = Path("research_docs")
    if not docs_dir.exists():
        docs_dir.mkdir(parents=True)
        (docs_dir / "sample1.md").write_text("# AI Agents\n\nAgents that can plan and execute.")
        (docs_dir / "sample2.md").write_text("# Workflows\n\nOrchestrate deterministic + agentic steps.")

    files = list(docs_dir.glob("*.md"))
    documents = [f.read_text() for f in files]

    return {
        **state,
        "documents": documents,
        "doc_count": len(files),
    }


async def format_report(state: ResearchState) -> ResearchState:
    """Deterministic step: Format final report"""
    from pathlib import Path

    themes = state.get("themes", "No themes")
    doc_count = state.get("doc_count", 0)

    report = f"""# Research Report

Documents Analyzed: {doc_count}

## Key Themes

{themes}

---
Generated by AmpBox: LangGraph + Amplifier@next
"""

    Path("research_report.md").write_text(report)

    return {
        **state,
        "report": report,
    }


async def research_workflow() -> dict:
    """
    Example workflow using LangGraph + Amplifier.

    Workflow:
    1. Load documents (deterministic - simple Python function)
    2. Analyze (agentic - Amplifier@next agent via AmplifierNode)
    3. Format report (deterministic - simple Python function)

    LangGraph handles: Orchestration, state, checkpointing
    Amplifier handles: Intelligence
    AmpBox provides: The bridge (AmplifierNode)
    """
    # Create LangGraph workflow
    workflow = StateGraph(ResearchState)

    # Add nodes (deterministic and agentic)
    workflow.add_node("load", load_documents)
    workflow.add_node(
        "analyze",
        AmplifierNode(agent_name="research_analyzer", task="Extract key themes from documents"),  # type: ignore[arg-type]
    )
    workflow.add_node("format", format_report)

    # Define flow
    workflow.set_entry_point("load")
    workflow.add_edge("load", "analyze")
    workflow.add_edge("analyze", "format")
    workflow.add_edge("format", END)

    # Compile and run
    app = workflow.compile()
    result = await app.ainvoke({"documents": [], "doc_count": 0, "themes": "", "report": ""})

    return result


if __name__ == "__main__":
    print("🚀 Running research workflow (LangGraph + Amplifier)\n")
    result = asyncio.run(research_workflow())

    print("\n✅ Workflow complete!")
    print(f"Documents: {result['doc_count']}")
    print("Report: research_report.md")
    print(f"State: {len(str(result))} bytes")
